### PR TITLE
Anon GOST3411

### PR DESCRIPTION
**Pull request by mikalv**

### CODE REVIEW

**Comment by mikalv** [comment]
We have reviewed in real life. Gonna merge.

**Comment by oyvkva** [comment]
Looks good!

**Comment by mikalv** [comment]
Let's give @switzer time for a final look and we're good to go :)

**Review by switzer — DISMISSED** [review]
Downloaded and ran test in OSX, others ran with Linux and Windows.  Looks great @mikalv !

**Review by orignal — DISMISSED** [review]
looks and works good

**Review by oyvkva — APPROVED** [review]
All good

**Pull request merged**
